# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DoubleEntryGenerator < Formula
  desc "Rule-based double-entry bookkeeping importer (from Alipay/WeChat/Huobi to Beancount)."
  homepage "https://github.com/deb-sig/double-entry-generator"
  version "1.7.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/deb-sig/double-entry-generator/releases/download/v1.7.0/double-entry-generator_1.7.0_Darwin_all.tar.gz"
    sha256 "b08f590d3fe6713d3233c1a5d46a7e9d72cf2a5d91e171d3f0dd7da745f64577"

    def install
      bin.install "double-entry-generator"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/deb-sig/double-entry-generator/releases/download/v1.7.0/double-entry-generator_1.7.0_Linux_x86_64.tar.gz"
      sha256 "daa81e8cda783b444af9d6eb17de6c5ed0da85502c5730e5e555c225bab31a4d"

      def install
        bin.install "double-entry-generator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deb-sig/double-entry-generator/releases/download/v1.7.0/double-entry-generator_1.7.0_Linux_arm64.tar.gz"
      sha256 "52db0c31a05f68f1927e4549d5b0195d9cbc1005f1609f18903859e1ea72fee8"

      def install
        bin.install "double-entry-generator"
      end
    end
  end

  def caveats
    <<~EOS
      Please run `double-entry-generator help` for more help.
    EOS
  end

  test do
    system "#{bin}/double-entry-generator version"
  end
end
